### ISSUE TITLE
The toolbar icons look too small in a 4K monitor

### ISSUE THREAD

**Issue by alsomar** [thomthom/quadface-tools#131]
Maybe .svg icons (instead png) could fix this.

**Comment by thomthom** [comment]
Yea, it would. Long time ago I began to work on SVG (and PDF for mac), https://github.com/thomthom/quadface-tools/tree/dev-vector-icons

But I've fallen short of time. There's a lot of icons!

**Comment by thomthom** [comment]
Maybe I could make a call for assistance to the community... 🤔

**Comment by alsomar** [comment]
Is there any guidelines or any specific detail to know for creating those icons? If so, I could vectorize them!

**Comment by thomthom** [comment]
I got a bunch done, but more is needed: https://github.com/thomthom/quadface-tools/tree/dev-vector-icons/Resources/Icons

Give a few days to see if I can setup a way to use this WIP so it's possible to view the SVG icons in SU. Then dig up my notes on technical requirements for them to work.

Somewhere I have a script that can convert SVG to PDF, so we don't really need to worry about the PDF versions.

**Comment by alsomar** [comment]
Hello again, I've remade the entire toolset. Hope it helps: 
[QFT_SVG.zip](https://github.com/thomthom/quadface-tools/files/6672087/QFT_SVG.zip)

**Comment by thomthom** [comment]
Wow!

That's amazing!

I need to make some adjustments to ensure they match the pixel grid. On a "normal" DPI monitor lines get blurry:

![image](https://user-images.githubusercontent.com/192418/122451794-d5010000-cfa8-11eb-9cce-543bb86d726b.png)

Looks like the stoke sizes are slightly larger than 1px.

![image](https://user-images.githubusercontent.com/192418/122451920-f82baf80-cfa8-11eb-912d-dd0a17ca7fb4.png)

What software did you use to edit? I'm not sure if Inkspace is displaying the SVGs entirely correctly.

**Comment by alsomar** [comment]
Oops, I think I used points (pt) instead of pixels (px), I guess that's why there's some strange sizes. I did it on Affinity Designer, a cheap alternative to Adobe Illustrator. I'll try to fix the sizes this weekend

**Comment by alsomar** [comment]
Hi there again. I've fixed the icons, now they should work fine
PS I've just updated the file, I found a couple of errors
[QFT_SVG_210619-1106.zip](https://github.com/thomthom/quadface-tools/files/6680376/QFT_SVG_210619-1106.zip) (updated)

**Comment by thomthom** [comment]
Sorry for slow response. Last week was hectic as I was finishing up things before my vacation started this weekend. Not sure if Iæll have time until I'm back from my trip next week.

**Comment by alsomar** [comment]
Don't worry and enjoy your well-deserved vacations!

**Comment by thomthom** [comment]
Ok, having a look at this again. For some reason several of the icons doesn't render properly. The SVG library SU uses is rather limited, so I assume the main issue is there. But it's a limitation we have.

![image](https://user-images.githubusercontent.com/192418/125852442-c22d728e-e3b1-4c76-8212-dd7f09614716.png)

It's strange how some of the icons render properly in either large or small variant, but not the other. I'll try to dig into what the difference might be.

Incidentally I'm seeing similar results using [Microsoft PowerToys' SVG shell extension](https://github.com/microsoft/PowerToys):

![image](https://user-images.githubusercontent.com/192418/125852456-0e7d8206-138b-4222-8877-00cca48a4ff1.png)

**Comment by thomthom** [comment]
Looking at the Connect icon there's something different:

![image](https://user-images.githubusercontent.com/192418/125853612-bf471628-9cec-412c-b6d2-7d0543870c05.png)

The 24x24 icon got rounded corners. but I'm not able to adjust the corner style in this variant. I'm not sure why. (I don't use Inkspace that much.)

Another Inkspace thing I don't fully understand is the image size. When I don't have anything select it looks like this:

![image](https://user-images.githubusercontent.com/192418/125853752-8f31f6cc-7085-4274-968f-02a1d1270876.png)

But to select the frame I need to double click a few times (assuming those are groups).

![image](https://user-images.githubusercontent.com/192418/125853860-b6322fb5-9cd5-42bf-bc7a-1e9cb88338be.png)

The image size is then different, and the line thickness is not 1.0 (even though it looks to be spot on.

**Comment by thomthom** [comment]
Hmm... the 24x24 don't actually have a stroke? It's a complex path instead?

Also, I really don't understand the Inkspace export settings:

![image](https://user-images.githubusercontent.com/192418/125854156-f35e18a3-5336-40f9-acf7-9b919aae6204.png)

I see 32x32 there under Export area, which makes sense because it's the size of the image. But what is "Image size" then?

**Comment by alsomar** [comment]
Hello there! I've been fixing the icons, getting stroke and fills into separate objets. I've also deleted the round corners, I guess it should work better now.
By the way, in order to avoid confusion with native SketchUp tools I'm proposing a couple of changes in the Line and Select icons, let me know what you think.
[QFT_SVG_210716_1230.zip](https://github.com/thomthom/quadface-tools/files/6830073/QFT_SVG_210716_1230.zip)

**Comment by thomthom** [comment]
> By the way, in order to avoid confusion with native SketchUp tools I'm proposing a couple of changes in the Line and Select icons, let me know what you think.

Yes, I like that. 👍

I'm seeing issues with the icons still:

![image](https://user-images.githubusercontent.com/192418/125943996-393168c4-8520-4546-9039-27b6df1a46d5.png)

Any ideas what the difference might be? I'm not able to pin down what triggers the black area. And the Explorer preview displays everything fine this time, so it's only in SU. (I really wish we'd update the SVG library.)

Btw, are you able to test the icons yourself? I can make a custom RBZ with the dev build that loads the SVG.

Also, there are two files that needs renaming:

```
WireframeToQuad_16.svg > WireframeToQuads_16.svg
WireframeToQuad_24.svg > WireframeToQuads_24.svg
```

**Comment by alsomar** [comment]
> Any ideas what the difference might be? I'm not able to pin down what triggers the black area. And the Explorer preview displays everything fine this time, so it's only in SU. (I really wish we'd update the SVG library.)

I'm going to look into those svg files, let's see if I find something

> Btw, are you able to test the icons yourself? I can make a custom RBZ with the dev build that loads the SVG.

It would be awesome, that way I wouldn't bother you as much as now!

> Also, there are two files that needs renaming:
> WireframeToQuad_16.svg > WireframeToQuads_16.svg
> WireframeToQuad_24.svg > WireframeToQuads_24.svg

Ok!

**Comment by thomthom** [comment]
Here you go: (Rename the `.zip` to `.rbz`)

[TT_QuadFaceTools-rename-to-rbz.zip](https://github.com/thomthom/quadface-tools/files/6830520/TT_QuadFaceTools-rename-to-rbz.zip)

> It would be awesome, that way I wouldn't bother you as much as now!

No bother at all! I'm very thankful and humbled that you take the time to work on these icons which I've procrastinated away for so long.

**Comment by alsomar** [comment]
There was some strange empty rectangles in some icons. Looks like that was the problem. Now they're looking good!
![Captura de pantalla 2021-07-16 14 53 57](https://user-images.githubusercontent.com/33101705/125950959-ca666fed-8fbd-4e7e-8fd3-eb63ed936f9f.png)

I've checked them for both small and big size. Here they are:
[QFT_SVG_210716-1453.zip](https://github.com/thomthom/quadface-tools/files/6830733/QFT_SVG_210716-1453.zip)

**Comment by alsomar** [comment]
Aaaargh, there's a mistake in the smooth icon, let me fix it

**Comment by alsomar** [comment]
Ok, fixed. This should be the good one!
[QFT_SVG_210716-1714.zip](https://github.com/thomthom/quadface-tools/files/6831800/QFT_SVG_210716-1714.zip)

**Comment by thomthom** [comment]
Looking gooooood! :D

![image](https://user-images.githubusercontent.com/192418/126000985-d0b92df0-f722-4abb-a32b-6b5d0a36ffee.png)

There are some lines that seems to fall of the pixel grid. I'm guessing those are not easy to see on a high-DPI monitor. I'll see if I can make some tweaks then batch generate PDFs.

**Comment by thomthom** [comment]
![image](https://user-images.githubusercontent.com/192418/126062845-0be5d7ce-eecb-46fd-b22b-35b39f0bcb90.png)

Got the 24x24 icons aligned to the pixel grid. :)

**Comment by alsomar** [comment]
Great, now they're looking perfect!

**Comment by alsomar** [comment]
Just for the record, I've just learned how to do that kind of visual adjustments with my software (affinity designer)

**Comment by thomthom** [comment]
Back to work this week. Not having a lot of spare computer time. If you want to have a run at the 16x16 then the latest dev build is attached.

[TT_QuadFaceTools-RENAME-TO-RBZ.zip](https://github.com/thomthom/quadface-tools/files/6856182/TT_QuadFaceTools-RENAME-TO-RBZ.zip)

**Comment by alsomar** [comment]
Hi there again! I just tested your last dev build on FHD monitor and it looks nice on both small and large size. Good job!

**Comment by thomthom** [comment]
16x16 icons on a low-DPI monitor also looks good! I think we're ready to ship!

Thank you so much for your work on this! Open source collaboration for the win! :D

**Comment by thomthom** [comment]
Doh, need to generate PDF versions for mac!

**Comment by thomthom** [comment]
0.15.0 is live on Extension Warehouse and SketchUcation.
